
var imagequant = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(imagequant) {
  imagequant = imagequant || {};


var e;e||(e=typeof imagequant !== 'undefined' ? imagequant : {});var aa;e.ready=new Promise(function(a){aa=a});var r={},w;for(w in e)e.hasOwnProperty(w)&&(r[w]=e[w]);var ba=!1,y=!1,ca=!1,da=!1;ba="object"===typeof window;y="function"===typeof importScripts;ca="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;da=!ba&&!ca&&!y;var z="",ea,A,ha,ia;
if(ca)z=y?require("path").dirname(z)+"/":__dirname+"/",ea=function(a,b){ha||(ha=require("fs"));ia||(ia=require("path"));a=ia.normalize(a);return ha.readFileSync(a,b?null:"utf8")},A=function(a){a=ea(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||B("Assertion failed: undefined");return a},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",B),e.inspect=function(){return"[Emscripten Module object]"};
else if(da)"undefined"!=typeof read&&(ea=function(a){return read(a)}),A=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");"object"===typeof a||B("Assertion failed: undefined");return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ba||y)y?z=self.location.href:document.currentScript&&(z=document.currentScript.src),_scriptDir&&
(z=_scriptDir),0!==z.indexOf("blob:")?z=z.substr(0,z.lastIndexOf("/")+1):z="",ea=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},y&&(A=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var ja=e.print||console.log.bind(console),E=e.printErr||console.warn.bind(console);for(w in r)r.hasOwnProperty(w)&&(e[w]=r[w]);r=null;var F;e.wasmBinary&&(F=e.wasmBinary);var noExitRuntime;
e.noExitRuntime&&(noExitRuntime=e.noExitRuntime);"object"!==typeof WebAssembly&&B("no native wasm support detected");var G,ka=new WebAssembly.Table({initial:55,maximum:55,element:"anyfunc"}),la=!1,ma="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function na(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ma)return ma.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|l:(f&7)<<18|g<<12|l<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}
function oa(a,b,c){var d=H;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}}var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function qa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&ra[c];)++c;c<<=1;if(32<c-a&&pa)return pa.decode(H.subarray(a,c));c=0;for(d="";;){var f=I[a+2*c>>1];if(0==f||c==b/2)return d;++c;d+=String.fromCharCode(f)}}function sa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)I[b>>1]=a.charCodeAt(f),b+=2;I[b>>1]=0;return b-d}function ta(a){return 2*a.length}
function ua(a,b){for(var c=0,d="";!(c>=b/4);){var f=J[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d}function va(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}J[b>>2]=g;b+=4;if(b+4>c)break}J[b>>2]=0;return b-d}
function wa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var K,xa,H,I,ra,J,L,ya,za;function Aa(a){K=a;e.HEAP8=xa=new Int8Array(a);e.HEAP16=I=new Int16Array(a);e.HEAP32=J=new Int32Array(a);e.HEAPU8=H=new Uint8Array(a);e.HEAPU16=ra=new Uint16Array(a);e.HEAPU32=L=new Uint32Array(a);e.HEAPF32=ya=new Float32Array(a);e.HEAPF64=za=new Float64Array(a)}var Ba=e.INITIAL_MEMORY||16777216;
e.wasmMemory?G=e.wasmMemory:G=new WebAssembly.Memory({initial:Ba/65536,maximum:32768});G&&(K=G.buffer);Ba=K.byteLength;Aa(K);J[1612]=5249488;function Ca(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.ta;"number"===typeof c?void 0===b.la?e.dynCall_v(c):e.dynCall_vi(c,b.la):c(void 0===b.la?null:b.la)}}}var Da=[],Ea=[],Fa=[],Ga=[];function Ha(){var a=e.preRun.shift();Da.unshift(a)}var M=0,Ia=null,N=null;e.preloadedImages={};e.preloadedAudios={};
function B(a){if(e.onAbort)e.onAbort(a);ja(a);E(a);la=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ja(a){var b=O;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Ka(){return Ja("data:application/octet-stream;base64,")}var O="imagequant.wasm";if(!Ka()){var La=O;O=e.locateFile?e.locateFile(La,z):z+La}
function Ma(){try{if(F)return new Uint8Array(F);if(A)return A(O);throw"both async and sync fetching of the wasm failed";}catch(a){B(a)}}function Na(){return F||!ba&&!y||"function"!==typeof fetch||Ja("file://")?new Promise(function(a){a(Ma())}):fetch(O,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+O+"'";return a.arrayBuffer()}).catch(function(){return Ma()})}Ea.push({ta:function(){Oa()}});function Pa(){return 0<Pa.ga}
function Qa(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ra=void 0;function P(a){for(var b="";H[a];)b+=Ra[H[a++]];return b}var Q={},R={},Sa={};function Ta(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function Ua(a,b){a=Ta(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Va(a){var b=Error,c=Ua(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var Wa=void 0;function S(a){throw new Wa(a);}var Xa=void 0;function Ya(a){throw new Xa(a);}function Za(a,b,c){function d(k){k=c(k);k.length!==a.length&&Ya("Mismatched type converter count");for(var h=0;h<a.length;++h)T(a[h],k[h])}a.forEach(function(k){Sa[k]=b});var f=Array(b.length),g=[],l=0;b.forEach(function(k,h){R.hasOwnProperty(k)?f[h]=R[k]:(g.push(k),Q.hasOwnProperty(k)||(Q[k]=[]),Q[k].push(function(){f[h]=R[k];++l;l===g.length&&d(f)}))});0===g.length&&d(f)}
function T(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||S('type "'+d+'" must have a positive integer typeid pointer');if(R.hasOwnProperty(a)){if(c.wa)return;S("Cannot register type '"+d+"' twice")}R[a]=b;delete Sa[a];Q.hasOwnProperty(a)&&(b=Q[a],delete Q[a],b.forEach(function(f){f()}))}function $a(a){return{count:a.count,fa:a.fa,ha:a.ha,V:a.V,X:a.X,Y:a.Y,Z:a.Z}}
function ab(a){S(a.U.X.W.name+" instance already deleted")}var bb=!1;function cb(){}function db(a){--a.count.value;0===a.count.value&&(a.Y?a.Z.ea(a.Y):a.X.W.ea(a.V))}function eb(a){if("undefined"===typeof FinalizationGroup)return eb=function(b){return b},a;bb=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.V?db(c):console.warn("object already deleted: "+c.V)});eb=function(b){bb.register(b,b.U,b.U);return b};cb=function(b){bb.unregister(b.U)};return eb(a)}
var fb=void 0,gb=[];function hb(){for(;gb.length;){var a=gb.pop();a.U.fa=!1;a["delete"]()}}function U(){}var ib={};function jb(a,b){var c=e;if(void 0===c[a].aa){var d=c[a];c[a]=function(){c[a].aa.hasOwnProperty(arguments.length)||S("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].aa+")!");return c[a].aa[arguments.length].apply(this,arguments)};c[a].aa=[];c[a].aa[d.qa]=d}}
function kb(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].aa&&void 0!==e[a].aa[c])&&S("Cannot register public name '"+a+"' twice"),jb(a,a),e.hasOwnProperty(c)&&S("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].aa[c]=b):(e[a]=b,void 0!==c&&(e[a].Ca=c))}function lb(a,b,c,d,f,g,l,k){this.name=a;this.constructor=b;this.da=c;this.ea=d;this.$=f;this.ua=g;this.ia=l;this.sa=k}
function mb(a,b,c){for(;b!==c;)b.ia||S("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.ia(a),b=b.$;return a}function nb(a,b){if(null===b)return this.ma&&S("null is not a valid "+this.name),0;b.U||S('Cannot pass "'+V(b)+'" as a '+this.name);b.U.V||S("Cannot pass deleted object as a pointer of type "+this.name);return mb(b.U.V,b.U.X.W,this.W)}
function ob(a,b){if(null===b){this.ma&&S("null is not a valid "+this.name);if(this.ka){var c=this.ya();null!==a&&a.push(this.ea,c);return c}return 0}b.U||S('Cannot pass "'+V(b)+'" as a '+this.name);b.U.V||S("Cannot pass deleted object as a pointer of type "+this.name);!this.ja&&b.U.X.ja&&S("Cannot convert argument of type "+(b.U.Z?b.U.Z.name:b.U.X.name)+" to parameter type "+this.name);c=mb(b.U.V,b.U.X.W,this.W);if(this.ka)switch(void 0===b.U.Y&&S("Passing raw pointer to smart pointer is illegal"),
this.Aa){case 0:b.U.Z===this?c=b.U.Y:S("Cannot convert argument of type "+(b.U.Z?b.U.Z.name:b.U.X.name)+" to parameter type "+this.name);break;case 1:c=b.U.Y;break;case 2:if(b.U.Z===this)c=b.U.Y;else{var d=b.clone();c=this.za(c,pb(function(){d["delete"]()}));null!==a&&a.push(this.ea,c)}break;default:S("Unsupporting sharing policy")}return c}
function qb(a,b){if(null===b)return this.ma&&S("null is not a valid "+this.name),0;b.U||S('Cannot pass "'+V(b)+'" as a '+this.name);b.U.V||S("Cannot pass deleted object as a pointer of type "+this.name);b.U.X.ja&&S("Cannot convert argument of type "+b.U.X.name+" to parameter type "+this.name);return mb(b.U.V,b.U.X.W,this.W)}function rb(a){return this.fromWireType(L[a>>2])}function tb(a,b,c){if(b===c)return a;if(void 0===c.$)return null;a=tb(a,b,c.$);return null===a?null:c.sa(a)}var ub={};
function vb(a,b){for(void 0===b&&S("ptr should not be undefined");a.$;)b=a.ia(b),a=a.$;return ub[b]}function wb(a,b){b.X&&b.V||Ya("makeClassHandle requires ptr and ptrType");!!b.Z!==!!b.Y&&Ya("Both smartPtrType and smartPtr must be specified");b.count={value:1};return eb(Object.create(a,{U:{value:b}}))}
function W(a,b,c,d){this.name=a;this.W=b;this.ma=c;this.ja=d;this.ka=!1;this.ea=this.za=this.ya=this.pa=this.Aa=this.xa=void 0;void 0!==b.$?this.toWireType=ob:(this.toWireType=d?nb:qb,this.ba=null)}function xb(a,b,c){e.hasOwnProperty(a)||Ya("Replacing nonexistant public symbol");void 0!==e[a].aa&&void 0!==c?e[a].aa[c]=b:(e[a]=b,e[a].qa=c)}
function X(a,b){a=P(a);var c=e["dynCall_"+a];for(var d=[],f=1;f<a.length;++f)d.push("a"+f);f="return function dynCall_"+(a+"_"+b)+"("+d.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall","rawFunction",f+"};\n"))(c,b);"function"!==typeof c&&S("unknown function pointer with signature "+a+": "+b);return c}var yb=void 0;function zb(a){a=Ab(a);var b=P(a);Y(a);return b}
function Bb(a,b){function c(g){f[g]||R[g]||(Sa[g]?Sa[g].forEach(c):(d.push(g),f[g]=!0))}var d=[],f={};b.forEach(c);throw new yb(a+": "+d.map(zb).join([", "]));}function Cb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Db(a,b,c){a instanceof Object||S(c+' with invalid "this": '+a);a instanceof b.W.constructor||S(c+' incompatible with "this" of type '+a.constructor.name);a.U.V||S("cannot call emscripten binding method "+c+" on deleted object");return mb(a.U.V,a.U.X.W,b.W)}
var Eb=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Fb(a){4<a&&0===--Z[a].na&&(Z[a]=void 0,Eb.push(a))}function pb(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Eb.length?Eb.pop():Z.length;Z[b]={na:1,value:a};return b}}function V(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Gb(a,b){switch(b){case 2:return function(c){return this.fromWireType(ya[c>>2])};case 3:return function(c){return this.fromWireType(za[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Hb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ua(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Ib(a,b){for(var c=[],d=0;d<a;d++)c.push(J[(b>>2)+d]);return c}function Jb(a,b,c){switch(b){case 0:return c?function(d){return xa[d]}:function(d){return H[d]};case 1:return c?function(d){return I[d>>1]}:function(d){return ra[d>>1]};case 2:return c?function(d){return J[d>>2]}:function(d){return L[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}for(var Kb=[null,[],[]],Lb=Array(256),Mb=0;256>Mb;++Mb)Lb[Mb]=String.fromCharCode(Mb);Ra=Lb;Wa=e.BindingError=Va("BindingError");
Xa=e.InternalError=Va("InternalError");U.prototype.isAliasOf=function(a){if(!(this instanceof U&&a instanceof U))return!1;var b=this.U.X.W,c=this.U.V,d=a.U.X.W;for(a=a.U.V;b.$;)c=b.ia(c),b=b.$;for(;d.$;)a=d.ia(a),d=d.$;return b===d&&c===a};U.prototype.clone=function(){this.U.V||ab(this);if(this.U.ha)return this.U.count.value+=1,this;var a=eb(Object.create(Object.getPrototypeOf(this),{U:{value:$a(this.U)}}));a.U.count.value+=1;a.U.fa=!1;return a};
U.prototype["delete"]=function(){this.U.V||ab(this);this.U.fa&&!this.U.ha&&S("Object already scheduled for deletion");cb(this);db(this.U);this.U.ha||(this.U.Y=void 0,this.U.V=void 0)};U.prototype.isDeleted=function(){return!this.U.V};U.prototype.deleteLater=function(){this.U.V||ab(this);this.U.fa&&!this.U.ha&&S("Object already scheduled for deletion");gb.push(this);1===gb.length&&fb&&fb(hb);this.U.fa=!0;return this};W.prototype.va=function(a){this.pa&&(a=this.pa(a));return a};
W.prototype.oa=function(a){this.ea&&this.ea(a)};W.prototype.argPackAdvance=8;W.prototype.readValueFromPointer=rb;W.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
W.prototype.fromWireType=function(a){function b(){return this.ka?wb(this.W.da,{X:this.xa,V:c,Z:this,Y:a}):wb(this.W.da,{X:this,V:a})}var c=this.va(a);if(!c)return this.oa(a),null;var d=vb(this.W,c);if(void 0!==d){if(0===d.U.count.value)return d.U.V=c,d.U.Y=a,d.clone();d=d.clone();this.oa(a);return d}d=this.W.ua(c);d=ib[d];if(!d)return b.call(this);d=this.ja?d.ra:d.pointerType;var f=tb(c,this.W,d.W);return null===f?b.call(this):this.ka?wb(d.W.da,{X:d,V:f,Z:this,Y:a}):wb(d.W.da,{X:d,V:f})};
e.getInheritedInstanceCount=function(){return Object.keys(ub).length};e.getLiveInheritedInstances=function(){var a=[],b;for(b in ub)ub.hasOwnProperty(b)&&a.push(ub[b]);return a};e.flushPendingDeletes=hb;e.setDelayFunction=function(a){fb=a;gb.length&&fb&&fb(hb)};yb=e.UnboundTypeError=Va("UnboundTypeError");e.count_emval_handles=function(){for(var a=0,b=5;b<Z.length;++b)void 0!==Z[b]&&++a;return a};e.get_first_emval=function(){for(var a=5;a<Z.length;++a)if(void 0!==Z[a])return Z[a];return null};
var Ob={o:function(a){return Nb(a)},n:function(a){"uncaught_exception"in Pa?Pa.ga++:Pa.ga=1;throw a;},v:function(a,b,c,d,f){var g=Qa(c);b=P(b);T(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,k){return k?d:f},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var k=xa;else if(2===c)k=I;else if(4===c)k=J;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(k[l>>g])},ba:null})},p:function(a,b,c,d,f,g,l,k,h,p,m,q,t){m=P(m);g=X(f,g);k&&(k=X(l,
k));p&&(p=X(h,p));t=X(q,t);var u=Ta(m);kb(u,function(){Bb("Cannot construct "+m+" due to unbound types",[d])});Za([a,b,c],d?[d]:[],function(n){n=n[0];if(d){var D=n.W;var v=D.da}else v=U.prototype;n=Ua(u,function(){if(Object.getPrototypeOf(this)!==x)throw new Wa("Use 'new' to construct "+m);if(void 0===C.ga)throw new Wa(m+" has no accessible constructor");var sb=C.ga[arguments.length];if(void 0===sb)throw new Wa("Tried to invoke ctor of "+m+" with invalid number of parameters ("+arguments.length+") - expected ("+
Object.keys(C.ga).toString()+") parameters instead!");return sb.apply(this,arguments)});var x=Object.create(v,{constructor:{value:n}});n.prototype=x;var C=new lb(m,n,x,t,D,g,k,p);D=new W(m,C,!0,!1);v=new W(m+"*",C,!1,!1);var fa=new W(m+" const*",C,!1,!0);ib[a]={pointerType:v,ra:fa};xb(u,n);return[D,v,fa]})},e:function(a,b,c,d,f,g,l,k,h,p){b=P(b);f=X(d,f);Za([],[a],function(m){m=m[0];var q=m.name+"."+b,t={get:function(){Bb("Cannot access "+q+" due to unbound types",[c,l])},enumerable:!0,configurable:!0};
h?t.set=function(){Bb("Cannot access "+q+" due to unbound types",[c,l])}:t.set=function(){S(q+" is a read-only property")};Object.defineProperty(m.W.da,b,t);Za([],h?[c,l]:[c],function(u){var n=u[0],D={get:function(){var x=Db(this,m,q+" getter");return n.fromWireType(f(g,x))},enumerable:!0};if(h){h=X(k,h);var v=u[1];D.set=function(x){var C=Db(this,m,q+" setter"),fa=[];h(p,C,v.toWireType(fa,x));Cb(fa)}}Object.defineProperty(m.W.da,b,D);return[]});return[]})},u:function(a,b){b=P(b);T(a,{name:b,fromWireType:function(c){var d=
Z[c].value;Fb(c);return d},toWireType:function(c,d){return pb(d)},argPackAdvance:8,readValueFromPointer:rb,ba:null})},j:function(a,b,c){c=Qa(c);b=P(b);T(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+V(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:Gb(b,c),ba:null})},d:function(a,b,c,d,f,g){var l=Ib(b,c);a=P(a);f=X(d,f);kb(a,function(){Bb("Cannot call "+a+" due to unbound types",
l)},b-1);Za([],l,function(k){var h=[k[0],null].concat(k.slice(1)),p=k=a,m=f,q=h.length;2>q&&S("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var t=null!==h[1]&&!1,u=!1,n=1;n<h.length;++n)if(null!==h[n]&&void 0===h[n].ba){u=!0;break}var D="void"!==h[0].name,v="",x="";for(n=0;n<q-2;++n)v+=(0!==n?", ":"")+"arg"+n,x+=(0!==n?", ":"")+"arg"+n+"Wired";p="return function "+Ta(p)+"("+v+") {\nif (arguments.length !== "+(q-2)+") {\nthrowBindingError('function "+p+" called with ' + arguments.length + ' arguments, expected "+
(q-2)+" args!');\n}\n";u&&(p+="var destructors = [];\n");var C=u?"destructors":"null";v="throwBindingError invoker fn runDestructors retType classParam".split(" ");m=[S,m,g,Cb,h[0],h[1]];t&&(p+="var thisWired = classParam.toWireType("+C+", this);\n");for(n=0;n<q-2;++n)p+="var arg"+n+"Wired = argType"+n+".toWireType("+C+", arg"+n+"); // "+h[n+2].name+"\n",v.push("argType"+n),m.push(h[n+2]);t&&(x="thisWired"+(0<x.length?", ":"")+x);p+=(D?"var rv = ":"")+"invoker(fn"+(0<x.length?", ":"")+x+");\n";if(u)p+=
"runDestructors(destructors);\n";else for(n=t?1:2;n<h.length;++n)q=1===n?"thisWired":"arg"+(n-2)+"Wired",null!==h[n].ba&&(p+=q+"_dtor("+q+"); // "+h[n].name+"\n",v.push(q+"_dtor"),m.push(h[n].ba));D&&(p+="var ret = retType.fromWireType(rv);\nreturn ret;\n");v.push(p+"}\n");h=Hb(v).apply(null,m);xb(k,h,b-1);return[]})},b:function(a,b,c,d,f){function g(p){return p}b=P(b);-1===f&&(f=4294967295);var l=Qa(c);if(0===d){var k=32-8*c;g=function(p){return p<<k>>>k}}var h=-1!=b.indexOf("unsigned");T(a,{name:b,
fromWireType:g,toWireType:function(p,m){if("number"!==typeof m&&"boolean"!==typeof m)throw new TypeError('Cannot convert "'+V(m)+'" to '+this.name);if(m<d||m>f)throw new TypeError('Passing a number "'+V(m)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return h?m>>>0:m|0},argPackAdvance:8,readValueFromPointer:Jb(b,l,0!==d),ba:null})},a:function(a,b,c){function d(g){g>>=2;var l=L;return new f(K,l[g+1],l[g])}var f=[Int8Array,Uint8Array,
Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=P(c);T(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{wa:!0})},k:function(a,b){b=P(b);var c="std::string"===b;T(a,{name:b,fromWireType:function(d){var f=L[d>>2];if(c)for(var g=d+4,l=0;l<=f;++l){var k=d+4+l;if(0==H[k]||l==f){g=g?na(H,g,k-g):"";if(void 0===h)var h=g;else h+=String.fromCharCode(0),h+=g;g=k+1}}else{h=Array(f);for(l=0;l<f;++l)h[l]=String.fromCharCode(H[d+4+l]);h=h.join("")}Y(d);return h},
toWireType:function(d,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||S("Cannot pass non-string to std::string");var l=(c&&g?function(){for(var p=0,m=0;m<f.length;++m){var q=f.charCodeAt(m);55296<=q&&57343>=q&&(q=65536+((q&1023)<<10)|f.charCodeAt(++m)&1023);127>=q?++p:p=2047>=q?p+2:65535>=q?p+3:p+4}return p}:function(){return f.length})(),k=Nb(4+l+1);L[k>>2]=l;if(c&&g)oa(f,k+4,l+1);else if(g)for(g=
0;g<l;++g){var h=f.charCodeAt(g);255<h&&(Y(k),S("String has UTF-16 code units that do not fit in 8 bits"));H[k+4+g]=h}else for(g=0;g<l;++g)H[k+4+g]=f[g];null!==d&&d.push(Y,k);return k},argPackAdvance:8,readValueFromPointer:rb,ba:function(d){Y(d)}})},f:function(a,b,c){c=P(c);if(2===b){var d=qa;var f=sa;var g=ta;var l=function(){return ra};var k=1}else 4===b&&(d=ua,f=va,g=wa,l=function(){return L},k=2);T(a,{name:c,fromWireType:function(h){for(var p=L[h>>2],m=l(),q,t=h+4,u=0;u<=p;++u){var n=h+4+u*b;
if(0==m[n>>k]||u==p)t=d(t,n-t),void 0===q?q=t:(q+=String.fromCharCode(0),q+=t),t=n+b}Y(h);return q},toWireType:function(h,p){"string"!==typeof p&&S("Cannot pass non-string to C++ string type "+c);var m=g(p),q=Nb(4+m+b);L[q>>2]=m>>k;f(p,q+4,m+b);null!==h&&h.push(Y,q);return q},argPackAdvance:8,readValueFromPointer:rb,ba:function(h){Y(h)}})},m:function(a,b){b=P(b);T(a,{Ba:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},h:Fb,w:function(a){4<a&&(Z[a].na+=1)},l:function(a,
b){var c=R[a];void 0===c&&S("_emval_take_value has unknown type "+zb(a));a=c.readValueFromPointer(b);return pb(a)},g:function(){B()},s:function(a,b,c){H.copyWithin(a,b,b+c)},c:function(a){a>>>=0;var b=H.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{G.grow(Math.min(2147483648,d)-K.byteLength+65535>>>16);Aa(G.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},t:function(){return 0},
q:function(){},i:function(a,b,c,d){for(var f=0,g=0;g<c;g++){for(var l=J[b+8*g>>2],k=J[b+(8*g+4)>>2],h=0;h<k;h++){var p=H[l+h],m=Kb[a];0===p||10===p?((1===a?ja:E)(na(m,0)),m.length=0):m.push(p)}f+=k}J[d>>2]=f;return 0},memory:G,r:function(){},table:ka};
(function(){function a(f){e.asm=f.exports;M--;e.monitorRunDependencies&&e.monitorRunDependencies(M);0==M&&(null!==Ia&&(clearInterval(Ia),Ia=null),N&&(f=N,N=null,f()))}function b(f){a(f.instance)}function c(f){return Na().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){E("failed to asynchronously prepare wasm: "+g);B(g)})}var d={a:Ob};M++;e.monitorRunDependencies&&e.monitorRunDependencies(M);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return E("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){if(F||"function"!==typeof WebAssembly.instantiateStreaming||Ka()||Ja("file://")||"function"!==typeof fetch)return c(b);fetch(O,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){E("wasm streaming compile failed: "+g);E("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var Oa=e.___wasm_call_ctors=function(){return(Oa=e.___wasm_call_ctors=e.asm.x).apply(null,arguments)},Nb=e._malloc=function(){return(Nb=e._malloc=e.asm.y).apply(null,arguments)},Y=e._free=function(){return(Y=e._free=e.asm.z).apply(null,arguments)},Ab=e.___getTypeName=function(){return(Ab=e.___getTypeName=e.asm.A).apply(null,arguments)};e.___embind_register_native_and_builtin_types=function(){return(e.___embind_register_native_and_builtin_types=e.asm.B).apply(null,arguments)};
e.dynCall_ii=function(){return(e.dynCall_ii=e.asm.C).apply(null,arguments)};e.dynCall_vi=function(){return(e.dynCall_vi=e.asm.D).apply(null,arguments)};e.dynCall_iii=function(){return(e.dynCall_iii=e.asm.E).apply(null,arguments)};e.dynCall_viii=function(){return(e.dynCall_viii=e.asm.F).apply(null,arguments)};e.dynCall_iiiiiif=function(){return(e.dynCall_iiiiiif=e.asm.G).apply(null,arguments)};e.dynCall_viiiiif=function(){return(e.dynCall_viiiiif=e.asm.H).apply(null,arguments)};
e.dynCall_iiiiif=function(){return(e.dynCall_iiiiif=e.asm.I).apply(null,arguments)};e.dynCall_viiiif=function(){return(e.dynCall_viiiif=e.asm.J).apply(null,arguments)};e.dynCall_i=function(){return(e.dynCall_i=e.asm.K).apply(null,arguments)};e.dynCall_v=function(){return(e.dynCall_v=e.asm.L).apply(null,arguments)};e.dynCall_vif=function(){return(e.dynCall_vif=e.asm.M).apply(null,arguments)};e.dynCall_iidiiii=function(){return(e.dynCall_iidiiii=e.asm.N).apply(null,arguments)};
e.dynCall_vii=function(){return(e.dynCall_vii=e.asm.O).apply(null,arguments)};e.dynCall_iiii=function(){return(e.dynCall_iiii=e.asm.P).apply(null,arguments)};e.dynCall_jiji=function(){return(e.dynCall_jiji=e.asm.Q).apply(null,arguments)};e.dynCall_viiiiii=function(){return(e.dynCall_viiiiii=e.asm.R).apply(null,arguments)};e.dynCall_viiiii=function(){return(e.dynCall_viiiii=e.asm.S).apply(null,arguments)};e.dynCall_viiii=function(){return(e.dynCall_viiii=e.asm.T).apply(null,arguments)};var Pb;
N=function Qb(){Pb||Rb();Pb||(N=Qb)};
function Rb(){function a(){if(!Pb&&(Pb=!0,e.calledRun=!0,!la)){Ca(Ea);Ca(Fa);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();Ga.unshift(b)}Ca(Ga)}}if(!(0<M)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ha();Ca(Da);0<M||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}
e.run=Rb;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();noExitRuntime=!0;Rb();


  return imagequant.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = imagequant;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return imagequant; });
    else if (typeof exports === 'object')
      exports["imagequant"] = imagequant;
    